version: '3.3'

services:
   keycloak:
     image: jboss/keycloak
     environment:
      - KEYCLOAK_USER=root
      - KEYCLOAK_PASSWORD=root
     ports:
      - 8080:8080
     network_mode: host

   vault:
     image: vault
     environment:
       - VAULT_DEV_ROOT_TOKEN_ID=myroot
       - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
     ports:
       - 8200:8200
     cap_add:
       - IPC_LOCK
     network_mode: host
